- name: Upload command files
  block:
  - name: Split command files
    set_fact:
      computed_run_command_files: "{{ _run_command_files.split(':') }}"
  - name: Create temporary directory for command files
    tempfile:
      state: directory
    register: command_files_tempdir_output
  - name: Copy command files
    copy:
      src: "{{ item }}"
      dest: "{{ tempfile_output.path }}/"
    with_items: "{{ computed_run_command_files }}"
  when: _run_command_files is defined