stages:
jobs:
  include:
    - stage: "docker"
      name: "ansible test"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/ansible_localhost_connection
    - stage: "docker"
      name: "mail server"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/mocked_mail_server