stages:
  # Compilation, tests, testing database creation scripts
  - "compilation, unit tests, database creation tests"
  - "integration tests"
jobs:
  include:
    - stage: "compilation, unit tests, database creation tests"
      name: "Database creation tests"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats