stages:
  - "docker"
  - "ansible-playbooks"
  - "docker-compose"
jobs:
  include:
    - stage: "docker"
      name: "ansible 2.3 test"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: $TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin/bats $TRAVIS_BUILD_DIR/bats/ansible_localhost_connection/ansible_2-3_server_image.bats
    - stage: "docker"
      name: "ansible 2.8 test"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: $TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin/bats $TRAVIS_BUILD_DIR/bats/ansible_localhost_connection/ansible_server_image.bats
    - stage: "docker"
      name: "mail server"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/mocked_mail_server
    - stage: "docker"
      name: "ssh server"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/ssh_server
    - stage: "docker"
      name: "ssh server with password login"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
        - apt-get install -y expect || yum install -y expect
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/ssh_server_with_password_login
    - stage: "ansible-playbooks"
      name: "ansible playbooks"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
        - bats/ansible_playbooks/build_ansible_server_image.sh images/ansible_server
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && export ANSIBLE_SERVER_IMAGE_CREATED=true && bats -rt bats/ansible_playbooks
    - stage: "docker-compose"
      name: "ansible with ssh server"
      language: bash
      sudo: true
      before_install:
        # Install bats-core with version 1.1.0 when package will be available (see https://github.com/bats-core/bats-core/issues/103)
        - .travis/bats/bats-core-installation.sh "$TRAVIS_BUILD_DIR/.travis/bats"
      services:
        - docker
      script: export PATH="$TRAVIS_BUILD_DIR/.travis/bats/bats-core/bin:$PATH" && bats -rt bats/ansible_with_ssh_server