version: '2'
services:
  test_ssh_server:
    build: ./../ssh_server
    container_name: test_ssh_server_container
    tty: true
    volumes:
      - ssh_keys_volume:/ssh_keys_vol/:rw

  ansible_machine:
    build: ./../ansible_server
    container_name: ansible_machine_container
    tty: true
    volumes:
      - $ANSIBLE_SERVER_DIR/ansible_project:/project
      - ssh_keys_volume:/ssh_keys_vol/:ro

volumes:
  ssh_keys_volume: