- debug:
    msg: "{{ loop_item }}"
- set_fact:
    computed_failed_executions_list: "{{ computed_failed_executions_list }} {{ loop_item.async_result_item.item }}"
  when: loop_item.failed and loop_item.finished != 0

- set_fact:
    computed_succeeded_executions_list: "{{ computed_succeeded_executions_list }} {{ loop_item.async_result_item.item }}"
  when: not loop_item.failed

- set_fact:
    computed_unfinished_executions_list: "{{ computed_unfinished_executions_list }} {{ loop_item.async_result_item.item }}"
  when: loop_item.failed and loop_item.finished == 0

- set_fact:
    _command_execution_failed: True
  when: loop_item.failed