version: '2'
services:
  centos_im:
    build: .
    tty: true
  # https://github.com/digiPlant/docker-fake-smtp
  fakesmtp:
    image: digiplant/fake-smtp
    ports:
      - "1025:25"

    volumes:
      - ./email:/var/mail

#  mailhog:
#    image: mailhog/mailhog:v1.0.0
#    ports:
#      - "1025:1025"
#      - "8025:8025"