- name: Run passed command
  hosts: "{{ hosts_group }}"
  tasks:
    - debug:
        msg: "{{ 'Szymon' | greetings_statement }}"
    - debug:
        msg: "{{ inventory_hostname | host_location_statement }}"