- name: Run passed command
  hosts: localhost
  connection: local
  tasks:
    - name: Split command items
      set_fact:
        computed_command_items: "{{ _command_items.split(':') }}"
    - debug:
        msg: "{{ computed_command_items }}"
    - include_tasks: ./tasks/run_command_for_items/item_executor.yml
      with_items: "{{ computed_command_items }}"